package tinyoai

import (
	"context"
	"encoding/binary"
	"encoding/json"
	"math"
	"os"
	"path/filepath"
	"runtime"
	"testing"
	"time"
)

// A fixed-size JSON header lets the trace remain a valid safetensors file
// after every completed row, including an early numerical failure. No model
// weights are saved here: only the Go logits generated by this test.
type logitTrace struct {
	file       *os.File
	rows, cols int
}

// newLogitTrace creates an optional safetensors logit trace with a fixed-size
// header reservation and test-managed cleanup. An empty path disables
// recording.
func newLogitTrace(t *testing.T, path string, cols int) *logitTrace {
	t.Helper()
	if path == "" {
		return nil
	}
	f, err := os.Create(path)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { f.Sync(); f.Close() })
	var length [8]byte
	binary.LittleEndian.PutUint64(length[:], 512)
	if _, err := f.Write(length[:]); err != nil {
		t.Fatal(err)
	}
	return &logitTrace{file: f, cols: cols}
}

// append records one logit row and updates the trace shape so completed rows
// remain readable after a numerical failure. A nil trace is a no-op; every 32
// rows are synced to disk.
func (w *logitTrace) append(t *testing.T, row []float32) {
	t.Helper()
	if w == nil {
		return
	}
	data := make([]byte, 4*len(row))
	for i, v := range row {
		binary.LittleEndian.PutUint32(data[i*4:], math.Float32bits(v))
	}
	if _, err := w.file.WriteAt(data, 520+int64(w.rows*w.cols*4)); err != nil {
		t.Fatal(err)
	}
	w.rows++
	header, err := json.Marshal(map[string]tensorInfo{"logits": {Dtype: "F32", Shape: []int{w.rows, w.cols}, Offsets: []int64{0, int64(w.rows * w.cols * 4)}}})
	if err != nil {
		t.Fatal(err)
	}
	if len(header) > 512 {
		t.Fatal("trace header too large")
	}
	for len(header) < 512 {
		header = append(header, ' ')
	}
	if _, err := w.file.WriteAt(header, 8); err != nil {
		t.Fatal(err)
	}
	if w.rows%32 == 0 {
		if err := w.file.Sync(); err != nil {
			t.Fatal(err)
		}
	}
}

// distributionKL computes KL(reference || actual) at temperature 1 over every
// logit, in float64. It centers logits before log-sum-exp and uses compensated
// summation to resolve divergence far below float32 precision. Only negative
// values within the expected float64 cancellation error are clamped to zero.
func distributionKL(reference, actual []float32) float64 {
	refMax, actualMax := float64(reference[argmax(reference)]), float64(actual[argmax(actual)])
	var refSum, actualSum float64
	for i := range reference {
		refSum += math.Exp(float64(reference[i]) - refMax)
		actualSum += math.Exp(float64(actual[i]) - actualMax)
	}
	refLog, actualLog := math.Log(refSum), math.Log(actualSum)
	var sum, compensation float64
	for i := range reference {
		r := float64(reference[i]) - refMax
		a := float64(actual[i]) - actualMax
		term := math.Exp(r) / refSum * ((r - refLog) - (a - actualLog))
		y := term - compensation
		next := sum + y
		compensation = (next - sum) - y
		sum = next
	}
	if sum < 0 && sum > -1e-12 {
		return 0
	}
	return sum
}

// TestDistributionKL checks identical distributions, invariance to a constant
// logit shift, and a two-outcome distribution with an analytic divergence.
func TestDistributionKL(t *testing.T) {
	x := []float32{1, 2, -4, 7}
	if v := distributionKL(x, x); v != 0 {
		t.Fatalf("identical distributions: %g", v)
	}
	y := []float32{101, 102, 96, 107}
	if v := distributionKL(x, y); v > 1e-12 || v < 0 {
		t.Fatalf("constant shift: %g", v)
	}
	// KL([1/2,1/2] || [1/4,3/4]) = log(4/3)/2.
	want := math.Log(4.0/3) / 2
	if v := distributionKL([]float32{0, 0}, []float32{0, float32(math.Log(3))}); math.Abs(v-want) > 1e-7 {
		t.Fatalf("KL = %g, want %g", v, want)
	}
}

// TestLogitTrace reads back a recorded multi-row safetensors trace and
// requires exact float values.
func TestLogitTrace(t *testing.T) {
	path := filepath.Join(t.TempDir(), "logits.safetensors")
	w := newLogitTrace(t, path, 3)
	w.append(t, []float32{1, -2, 3})
	w.append(t, []float32{4, 5, -6})
	p := openProbe(t, path)
	got, err := p.load("logits", 2, 3)
	if err != nil {
		t.Fatal(err)
	}
	for i, want := range []float32{1, -2, 3, 4, 5, -6} {
		if got.at(i) != want {
			t.Fatalf("saved logit %d: %g, want %g", i, got.at(i), want)
		}
	}
}

// TestClioGreedyParity is an opt-in full-vocabulary comparison with CPU
// float32 cached-token reference logits. Ordinary parity runs follow Go's own
// greedy trajectory and fail on argmax or KL divergence.
//
// TINYOAI_QUANTIZATION_COMPARISON=1 instead forces reference tokens into
// subsequent forwards, isolating lossy-weight drift without requiring
// identical argmax. Optional reports retain per-step KL, timings, memory, and
// logits.
func TestClioGreedyParity(t *testing.T) {
	dir, refDir := os.Getenv("TINYOAI_CLIO_DIR"), os.Getenv("TINYOAI_GREEDY_REFERENCE")
	// Lossy-weight comparisons must use identical input prefixes. This mode
	// reports quality drift without imposing exact greedy or tiny-KL parity.
	quality := os.Getenv("TINYOAI_QUANTIZATION_COMPARISON") == "1"
	if dir == "" || refDir == "" {
		t.Skip("set TINYOAI_CLIO_DIR and TINYOAI_GREEDY_REFERENCE")
	}
	data, err := os.ReadFile(filepath.Join(refDir, "reference.json"))
	if err != nil {
		t.Fatal(err)
	}
	var ref struct {
		Mode         string `json:"execution_mode"`
		PromptIDs    []int  `json:"prompt_ids"`
		GeneratedIDs []int  `json:"generated_ids"`
	}
	if err := json.Unmarshal(data, &ref); err != nil {
		t.Fatal(err)
	}
	if ref.Mode != "cpu-float32-cached-token" {
		t.Fatalf("incompatible reference mode %q", ref.Mode)
	}
	if len(ref.PromptIDs) == 0 || len(ref.GeneratedIDs) == 0 {
		t.Fatal("empty reference trajectory")
	}
	m, err := LoadStableLMWithOptions(dir, StableLMOptions{KVCache: os.Getenv("TINYOAI_KV_CACHE")})
	if err != nil {
		t.Fatal(err)
	}
	memoryAfterLoad := parityMemory()
	steps := len(ref.PromptIDs) + len(ref.GeneratedIDs) - 1
	if steps > m.config.MaxPositionEmbeddings {
		t.Fatalf("%d forward positions exceed context", steps)
	}
	if m.config.VocabSize != 65536 {
		t.Fatalf("Clio vocab size = %d", m.config.VocabSize)
	}
	probes := openProbe(t, filepath.Join(refDir, "logits.safetensors"))
	want, err := probes.load("logits", len(ref.GeneratedIDs), m.config.VocabSize)
	if err != nil {
		t.Fatal(err)
	}
	s := m.newState(steps)
	prefillProfile, decodeProfile := stableProfile{}, stableProfile{}
	s.profile = &prefillProfile
	start := time.Now()
	s.prefillDone = func(pos int) {
		if pos%256 == 0 || pos == len(ref.PromptIDs) {
			t.Logf("prefill %d/%d: %s", pos, len(ref.PromptIDs), time.Since(start).Round(time.Second))
		}
	}
	batched := os.Getenv("TINYOAI_PREFILL_BATCHED") == "1"
	if batched {
		t.Logf("batched prefill: %d tokens, batch size %d", len(ref.PromptIDs), prefillBatch)
		if err := m.prefill(context.Background(), ref.PromptIDs, 0, s); err != nil {
			t.Fatal(err)
		}
	} else {
		for pos, token := range ref.PromptIDs {
			if err := m.forward(context.Background(), token, pos, s, pos == len(ref.PromptIDs)-1); err != nil {
				t.Fatal(err)
			}
			if (pos+1)%64 == 0 {
				elapsed := time.Since(start)
				t.Logf("prefill %d/%d: %s; attention %.1f%%, KV writes %.1f%%", pos+1, len(ref.PromptIDs), elapsed.Round(time.Second),
					100*float64(prefillProfile["attention"])/float64(elapsed), 100*float64(prefillProfile["kv_write"])/float64(elapsed))
			}
		}
	}
	prefillSeconds := time.Since(start).Seconds()
	s.prefillDone = nil
	t.Logf("prefill finished in %.3fs (%.2f tokens/s)", prefillSeconds, float64(len(ref.PromptIDs))/prefillSeconds)
	memoryAfterPrefill := parityMemory()
	s.profile = &decodeProfile
	trace := newLogitTrace(t, os.Getenv("TINYOAI_PARITY_TRACE"), m.config.VocabSize)
	start = time.Now()
	var logitStats errorStats
	var maxKL, totalKL, decodeForwardSeconds float64
	perStep := make([]float64, len(ref.GeneratedIDs))
	for step, expected := range ref.GeneratedIDs {
		trace.append(t, s.logits)
		actual := int(argmax(s.logits))
		reference := tensorRow(want, step)
		if int(argmax(reference)) != expected {
			t.Fatalf("reference argmax disagrees with token at step %d", step)
		}
		kl := distributionKL(reference, s.logits)
		perStep[step] = kl
		if math.IsNaN(kl) || math.IsInf(kl, 0) || kl < 0 || (!quality && kl > 1e-7) {
			t.Fatalf("step %d: KL(reference || Go) = %g", step, kl)
		}
		logitStats.add(s.logits, reference)
		maxKL = math.Max(maxKL, kl)
		totalKL += kl
		if !quality && actual != expected {
			t.Fatalf("greedy diverged at step %d / position %d: Go=%d ref=%d, KL=%g", step, len(ref.PromptIDs)-1+step, actual, expected, kl)
		}
		if (step+1)%32 == 0 {
			t.Logf("output %d/%d: argmax matches %d/%d, max KL %.9g, elapsed %s", step+1, len(ref.GeneratedIDs), logitStats.top1, step+1, maxKL, time.Since(start).Round(time.Second))
			if decodeForwardSeconds > 0 {
				t.Logf("decode forward %.2f tokens/s; attention %.1f%%, KV writes %.1f%%", float64(step)/decodeForwardSeconds,
					100*decodeProfile["attention"].Seconds()/decodeForwardSeconds, 100*decodeProfile["kv_write"].Seconds()/decodeForwardSeconds)
			}
		}
		if step+1 < len(ref.GeneratedIDs) {
			input := actual
			if quality {
				input = expected
			}
			if input == m.config.EOSTokenID {
				t.Fatal("reference continues after EOS")
			}
			forwardStart := time.Now()
			if err := m.forward(context.Background(), input, len(ref.PromptIDs)+step, s, true); err != nil {
				t.Fatal(err)
			}
			decodeForwardSeconds += time.Since(forwardStart).Seconds()
		}
	}
	decodeSeconds := time.Since(start).Seconds()
	report := map[string]any{
		"model": dir, "weight_dtype": m.head.dtype, "teacher_forced_quantization_comparison": quality,
		"kv_cache_float16":  m.halfKV,
		"batched_prefill":   batched,
		"numerical_backend": numericalBackend(),
		"cache_layout":      "kv-head-position-channel", "max_attention_workers": min(runtime.GOMAXPROCS(0), m.config.NumAttentionHeads),
		"go_version": runtime.Version(), "goos": runtime.GOOS, "goarch": runtime.GOARCH, "gomaxprocs": runtime.GOMAXPROCS(0),
		"reference_mode": ref.Mode, "logits_file": os.Getenv("TINYOAI_PARITY_TRACE"),
		"prompt_tokens": len(ref.PromptIDs), "greedy_tokens": len(ref.GeneratedIDs), "last_forward_position": steps - 1,
		"argmax_matches": logitStats.top1, "max_kl": maxKL, "mean_kl": totalKL / float64(len(perStep)), "per_step_kl": perStep,
		"max_logit_error": logitStats.max, "rms_logit_error": math.Sqrt(logitStats.squared / float64(logitStats.n)),
		"prefill_seconds": prefillSeconds, "decode_seconds": decodeSeconds,
		"decode_forward_tokens": len(ref.GeneratedIDs) - 1, "decode_forward_seconds": decodeForwardSeconds,
		"prefill_stage_seconds": profileSeconds(prefillProfile), "decode_stage_seconds": profileSeconds(decodeProfile),
		"memory_after_load": memoryAfterLoad, "memory_after_prefill": memoryAfterPrefill, "memory_after_decode": parityMemory(),
	}
	if path := os.Getenv("TINYOAI_PARITY_REPORT"); path != "" {
		data, err := json.MarshalIndent(report, "", "  ")
		if err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, append(data, '\n'), 0600); err != nil {
			t.Fatal(err)
		}
	}
	t.Logf("%d prompt + %d greedy; final position %d; %s; max KL %.9g, mean KL %.9g", len(ref.PromptIDs), len(ref.GeneratedIDs), steps-1, logitStats, maxKL, totalKL/float64(len(perStep)))
}

// parityMemory records Go allocator counters and peak process RSS when the
// platform provides it; these quantities measure different scopes of memory.
func parityMemory() map[string]uint64 {
	var stats runtime.MemStats
	runtime.ReadMemStats(&stats)
	memory := map[string]uint64{
		"heap_alloc_bytes": stats.HeapAlloc, "heap_inuse_bytes": stats.HeapInuse,
		"heap_sys_bytes": stats.HeapSys, "runtime_sys_bytes": stats.Sys,
		"total_alloc_bytes": stats.TotalAlloc, "gc_cycles": uint64(stats.NumGC),
	}
	if rss, ok := peakRSS(); ok {
		memory["peak_rss_bytes"] = rss
	}
	return memory
}

// profileSeconds converts accumulated stage durations to seconds for a JSON
// measurement report.
func profileSeconds(profile stableProfile) map[string]float64 {
	seconds := make(map[string]float64, len(profile))
	for stage, elapsed := range profile {
		seconds[stage] = elapsed.Seconds()
	}
	return seconds
}
